# https://rust-lang.github.io/rustfmt/
brace_style = "AlwaysNextLine"
combine_control_expr = false
comment_width = 127
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
empty_item_single_line = true
enum_discrim_align_threshold = 127
fn_args_layout = "Vertical"
fn_single_line = true
force_explicit_abi = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "Vertical"
max_width = 127
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
spaces_around_ranges = true
struct_field_align_threshold = 127
struct_lit_single_line = false
tab_spaces = 2
trailing_comma = "Never"
trailing_semicolon = false
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
version = "Two"
wrap_comments = true
